name: CSM Demo Workflows
on:
 schedule:
   - cron: "*/55 8 * * *"

 workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run Desktop Tests
      continue-on-error: true
      env:
        SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
        SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        SCREENER_API_KEY: ${{ secrets.SCREENER_API_KEY }}
      run: mvn test -pl best-practice -Dtest=DesktopTests* -X
      
    - name: Run Failing Login Test
      continue-on-error: true
      env:
        SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
        SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        SCREENER_API_KEY: ${{ secrets.SCREENER_API_KEY }}
      run: mvn test -pl selenium-examples -Dtest=SeleniumLoginTest

    - name: RDC Native App Android
      continue-on-error: true
      env:
        SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
        SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        SCREENER_API_KEY: ${{ secrets.SCREENER_API_KEY }}
      run: mvn test -pl appium-examples -Dtest=AndroidNativeAppTest#shouldOpenApp -X


    - name: RDC Native App Android Dynamic test name
      continue-on-error: true
      env:
        SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
        SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        SCREENER_API_KEY: ${{ secrets.SCREENER_API_KEY }}
      run: |
        export ANDROID_APP=https://github.com/saucelabs/sample-app-mobile/releases/download/2.7.1/Android.SauceLabs.Mobile.Sample.app.2.7.1.apk
        mvn test -pl appium-examples -Dtest=AndroidNativeAppTest#setAppNameDynamically -X
        
    - name: RDC Native App IOS
      continue-on-error: true
      env:
        SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
        SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        SCREENER_API_KEY: ${{ secrets.SCREENER_API_KEY }}
      run: mvn test -pl appium-examples -Dtest=IOSNativeAppTest -X

    - name: RDC Web
      continue-on-error: true
      env:
        SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
        SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        SCREENER_API_KEY: ${{ secrets.SCREENER_API_KEY }}
      run: mvn test -pl best-practice -Dtest=Real* -X
